# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Crossfit Charlton
email: jeff@paladinwebgroup.com
description: >- # this means to ignore newlines until "baseurl:"
  Charlton's newest premier fitness facility
  Featuring CrossFit's own Affiliating Program in a new state of the art facility.
  Start Today with a Free 1-on-1 Intro

# Staging only
baseurl: "crossfitcharlton" # the subpath of your site, e.g. /blog

# Local and Production 
# baseurl: "" # the subpath of your site, e.g. /blog

url: "https://www.crossfitcharlton.com/" # the base hostname & protocol for your site, e.g. http://example.com
facebook_username: CrossFitCharlton
instagram_username:  crossfitcharlton
github_username:  jeffhow

# Build settings
# theme: custom
plugins:
  - jekyll-sitemap
  - jekyll-redirect-from

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - "README.md"
  - "**/README.md"
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
